### ISSUE TITLE
Possibility to set the starting points

### ISSUE THREAD

**Issue by kpeternyman** [ChrisHaPunkt/ha-stihl-imow#11]
In the app and in the API it is possible to set starting points (1 to 4), distance and frequency.
It would be nice to have this possibility in the integration as well.

I have two different perimeter wires in my garden.
I'm switching between them with a relay on a specific day of the week.
When i use perimeter wire number 2 i must set starting points beyond a narrow tunnel so that the imow follows the perimeter wire into the area i want to be mowed.

**Comment by klaaspiet** [comment]
This would be great i have the same question

**Comment by ChrisHaPunkt** [comment]
Using `startMowingFromPoint` as an action is already implemented and should work.
You can use this in a service call like this:
![grafik](https://github.com/ChrisHaPunkt/ha-stihl-imow/assets/4389395/f38f349f-c278-4b39-afe9-8d0252a1974d)
