### ISSUE TITLE
No config flow

### ISSUE THREAD

**Issue by jwmaas** [ChrisHaPunkt/ha-stihl-imow#2]
When I installed the ha-stihl-imow component, I did not get a configuration flow to add my login details.
I have installed by adding the depository to HACS, then installed the component. I have also restarted HA.

How to force the configuration flow to start?

**Comment by ChrisHaPunkt** [comment]
https://github.com/ChrisHaPunkt/ha-stihl-imow/issues/1#issuecomment-860200763

Should do the trick ;-)
![Screenshot_20210626-214446.jpg](https://user-images.githubusercontent.com/4389395/123524007-daa4c700-d6c7-11eb-9c97-1e46fbda020a.jpg)

![Screenshot_20210626-214516.jpg](https://user-images.githubusercontent.com/4389395/123524010-df697b00-d6c7-11eb-89d8-eeb21c2a5a09.jpg)

**Comment by jwmaas** [comment]
If I try to add the integration it does not show up, however it is installed. What to do?
I tried manually adding username and password via config.yaml, but no effect.


<img width="510" alt="Screenshot 2021-06-26 at 23 33 02" src="https://user-images.githubusercontent.com/16177874/123526395-e4cec180-d6d7-11eb-8456-4011b21cd74e.png">
<img width="731" alt="Screenshot 2021-06-26 at 23 33 41" src="https://user-images.githubusercontent.com/16177874/123526397-e5675800-d6d7-11eb-858a-d4949bc6be49.png">
<img width="721" alt="Screenshot 2021-06-26 at 23 35 44" src="https://user-images.githubusercontent.com/16177874/123526398-e5675800-d6d7-11eb-8c97-befc100bc7f4.png">
<img width="614" alt="Screenshot 2021-06-26 at 23 36 38" src="https://user-images.githubusercontent.com/16177874/123526399-e5ffee80-d6d7-11eb-8e17-0996b8faf6e8.png">

**Comment by ChrisHaPunkt** [comment]
Hmm, okay... After installing via HACS and restarting home assistant it should pop up in the "add integration" list. 
Config YAML configuration is not supported.
Are there any related error messages in your home assistant Log?

**Comment by jwmaas** [comment]
After installing and restarting HA I needed to refresh the integrations overview page before the new integration is visible. All is well now. Thanks.
