### ISSUE TITLE
Stopped working on HA 2023-12

### ISSUE THREAD

**Issue by tgilis** [ChrisHaPunkt/ha-stihl-imow#22]
The integration stopped working on HA 2023-12 with the error below.

`Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 08:32:58 (3 occurrences)
Last logged: 08:33:09

Unable to install package imow-webapi==0.7.8: ERROR: Cannot install imow-webapi==0.7.8 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by kabums** [comment]
same problem, older version

Logger: homeassistant.setup
Source: setup.py:221
First occurred: 7. Dezember 2023 um 23:56:21 (1 occurrences)
Last logged: 7. Dezember 2023 um 23:56:21

Setup failed for custom integration 'stihl_imow': Requirements for stihl_imow not found: ['imow-webapi==0.7.6'].

**Comment by ChrisHaPunkt** [comment]
Please feel free to update to 0.1.5, that should address the issue.
If the error persists, please reopen the issue.
