### ISSUE TITLE
Messing attributes

### ISSUE THREAD

**Issue by erd82** [ChrisHaPunkt/ha-stihl-imow#24]
What could be the reason that I cannot see the additional attributes next to the state?

![Screenshot_20240301_152949_Home Assistant.jpg](https://github.com/ChrisHaPunkt/ha-stihl-imow/assets/63564291/ecfa0a97-872e-44a0-a6a6-78f9d409707e)

Should it look like this? 
![Screenshot_20240301_153418_GitHub.jpg](https://github.com/ChrisHaPunkt/ha-stihl-imow/assets/63564291/23676945-165d-4fb7-bfac-1d1584ed8a42)

In the past I had an entity for each attribute. This seems to have changed?

PS: I have the RMI 422 PC.

**Comment by ChrisHaPunkt** [comment]
> In the past I had an entity for each attribute. This seems to have changed?

This is the case for the current beta release.

If you are not using the beta version, can you confirm that you see the attributes in the developer tools "states" view if you click on the entity?

**Comment by ChrisHaPunkt** [comment]
I'm not completely sure, but I think HA stopped showing the attributes of an entity in the Lovelace card

**Comment by erd82** [comment]
> > In the past I had an entity for each attribute. This seems to have changed?
> 
> This is the case for the current beta release.
> 
> If you are not using the beta version, can you confirm that you see the attributes in the developer tools "states" view if you click on the entity?
> 

No, unfortunately, I can not see the attributes there, as you already confirmed. And thanks for the hint with the beta ... In the past I was using the beta as it seemed. Now the other data is available again. Many thanks!!
