### ISSUE TITLE
Refreshing new data not working

### ISSUE THREAD

**Issue by iwanvandaele** [ChrisHaPunkt/ha-stihl-imow#6]
Hi,

I'm getting an timeout error times by times and the status of the imow is not refreshed, error in the log file:

2021-07-09 11:18:49 ERROR (MainThread) [custom_components.stihl_imow.binary_sensor] Timeout fetching imow_binarysensor data
2021-07-09 11:18:49 ERROR (MainThread) [custom_components.stihl_imow.switch] Timeout fetching imow_switch_entity data
2021-07-09 11:18:55 ERROR (MainThread) [custom_components.stihl_imow.sensor] Timeout fetching imow_sensor data
2021-07-09 12:08:30 ERROR (MainThread) [custom_components.stihl_imow.switch] Timeout fetching imow_switch_entity data
2021-07-09 12:08:30 ERROR (MainThread) [custom_components.stihl_imow.sensor] Timeout fetching imow_sensor data

When I reload the component the status is refreshed.
Version installed: 1.0.2

Homeassistant version: core-2021.7.1

Regards,
Iwan Vandaele

**Comment by Jarobwo** [comment]
the first version of your software updated the robot status very quickly, it was practically the same as in the imow application, now it does not change even for an hour

**Comment by ChrisHaPunkt** [comment]
Yeah, I see the same behaviour on all confiugurations which uses a version >  1.0.0
I'll spend more time today to look into this.

**Comment by ChrisHaPunkt** [comment]
I just released version 1.0.0rc12 where the update mechanism is re-structured. 

Please test and report back.

**Comment by ChrisHaPunkt** [comment]
Found another issue related, currently working on it. Stay tuned :)

**Comment by ChrisHaPunkt** [comment]
https://github.com/ChrisHaPunkt/ha-stihl-imow/releases/tag/v1.0.0rc15 should fix the issue.

**Comment by iwanvandaele** [comment]
Hi,

Tested it yesterday and the status update is working with version 1.0.0rc15.
Thx for solving the issue.

Regards,
Iwan Vandaele

**Comment by iwanvandaele** [comment]
I get now sometimes timeout of fetching data:

2021-07-13 09:23:56 ERROR (MainThread) [custom_components.stihl_imow] Timeout fetching imow_8a07d05ecbe7c6349b2b044bfdd7ab38 data
2021-07-13 09:25:09 ERROR (MainThread) [custom_components.stihl_imow] Timeout fetching imow_8a07d05ecbe7c6349b2b044bfdd7ab38 data

![image](https://user-images.githubusercontent.com/56552821/125409791-8df60700-e3bc-11eb-80de-8b0bada98c41.png)

Grey part is unavailable.

Installed version: v1.0.0rc16

**Comment by ChrisHaPunkt** [comment]
I'm staying in contact with stihl support regarding this issue. I'm thinking this is about security mechanisms kicking in on the upstream stihl server.

**Comment by erd82** [comment]
> I get now sometimes timeout of fetching data:
> 
> 2021-07-13 09:23:56 ERROR (MainThread) [custom_components.stihl_imow] Timeout fetching imow_8a07d05ecbe7c6349b2b044bfdd7ab38 data
> 2021-07-13 09:25:09 ERROR (MainThread) [custom_components.stihl_imow] Timeout fetching imow_8a07d05ecbe7c6349b2b044bfdd7ab38 data
> 
> ![image](https://user-images.githubusercontent.com/56552821/125409791-8df60700-e3bc-11eb-80de-8b0bada98c41.png)
> 
> Grey part is unavailable.
> 
> Installed version: v1.0.0rc16

This seems to be the same issue as I have (see 2nd issue) ... gaps where the sensors are unavailable:
https://community.home-assistant.io/t/stihl-imow-robotic-lawn-mower/303180/49

@ChrisHaPunkt, thanks so much for the persistent optimization!

**Comment by ChrisHaPunkt** [comment]
I reached out to STIHL because I think there is an upstream security mechanism kicking in. This leads to the timeouts which are amnifesting as "gaps" in the states.
There is an ongoing discussion over here: https://community.home-assistant.io/t/stihl-imow-robotic-lawn-mower/303180/49

**Comment by Jarobwo** [comment]
> Hi,
> 
> Tested it yesterday and the status update is working with version 1.0.0rc15.
> Thx for solving the issue.
> 
> Regards,
> Iwan Vandaele

Yes now is okkkk!!
