### ISSUE TITLE
Feature Request: Switch for the services

### ISSUE THREAD

**Issue by meistermolli** [ChrisHaPunkt/ha-stihl-imow#8]
Hi there, im happy, that you do this integration!

is there any way to get the services of the developer tools:
![Bildschirmfoto 2022-03-31 um 15 31 21](https://user-images.githubusercontent.com/55836556/161067291-345c13fb-8c56-433e-bfe5-e2b2b145b742.png)

to a switch or anything on the Lovelace like the child protection?
That I can start the service with my mobile app that hast no admin connection to the developer tools?

Maybe there is a workaround at this time that I dont know?

Thanks very much.

**Comment by ChrisHaPunkt** [comment]
Hi @meistermolli ,

there is native home assistant functionality for this. 
You can assign actions, like service calls, to several Lovelace elements. 
Have a look here:
https://www.home-assistant.io/dashboards/actions/
or here: https://community.home-assistant.io/t/call-service-button-from-lovelace/168656/8

**Comment by meistermolli** [comment]
Thanks!
